### ISSUE TITLE
Hacer los ejercicios del cuestionario previo

### ISSUE THREAD

**Issue by AzofeifaJ** [AzofeifaJ/Taller-de-Digitales_Grupo-4#38]
1. Javier
2. Javier
3. Javier
4. Javier
5. Johan
6. Johan
7. Alonso
8. Alonso

**Comment by Jsuare** [comment]
A cabo de subir mi parte del cuestionario previo, por favor revisar. Gracias

**Comment by AzofeifaJ** [comment]
Ya terminé mi parte del cuestionario previo, además me comentó Johan que ya terminó su parte

**Comment by AzofeifaJ** [comment]
Laboratorio_2/Cuestionario_Previo.md
